server:
  port: 33000

spring:
  application:
    name: 'smart-site-cloud-message-center'
  profiles:
    active: 'nacos-dev'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://ss2-test.4s-hk.com:5432/ssc?stringtype=unspecified
    username: postgres
    password: not4u2day
    driverClassName: org.postgresql.Driver
  r2dbc:
    url: r2dbc:pool:postgres://ss2-test.4s-hk.com:5432/ssc?stringtype=unspecified
    username: postgres
    password: not4u2day
  data:
    redis:
      host: 192.168.0.99
      port: 6379
      database: 9
      password: not4u2day

logging:
  config: 'classpath:smart-site-cloud-logback.xml'

p6e:
  cloud:
    common:
      version: 'SMART-SITE-CLOUD-MESSAGE-CENTER@3.1.0_VERSION_20250526185910561'
